export const States = [
  'AC',
  'AL',
  'AM',
  'AP',
  'BA',
  'CE',
  'DF',
  'ES',
  'GO',
  'MG',
  'MA',
  'MS',
  'MT',
  'PA',
  'PB',
  'PE',
  'PI',
  'PR',
  'RJ',
  'RN',
  'RO',
  'RR',
  'RS',
  'SP',
  'SC',
  'SE',
  'TO',
  'Ext.',
];

export const Options = {
  DISABITIES: [
    { value: '', label: 'Indeferente' },
    { value: 'Qualquer', label: 'Qualquer Tipo' },
    { value: 'Autismo', label: 'Autismo' },
    { value: 'Cadeirante', label: 'Cadeirante' },
    { value: 'Intelectual', label: 'Intelectual' },
    { value: 'Múltipla', label: 'Múltipla' },
  ],
  GRADES: [
    { value: '', label: '-----' },
    { value: '1º', label: '1º' },
    { value: '2º', label: '2º' },
    { value: '3º', label: '3º' },
    { value: '4º', label: '4º' },
    { value: '5º', label: '5º' },
  ],
  GROUPS: [
    { value: '', label: '-----' },
    { value: 'A', label: 'A' },
    { value: 'B', label: 'B' },
    { value: 'C', label: 'C' },
    { value: 'D', label: 'D' },
  ],
  PERIODS: [
    { value: 'Manhã', label: 'Manhã' },
    { value: 'Tarde', label: 'Tarde' },
  ],
};
